### ISSUE TITLE
Morning Scoping Session

### ISSUE THREAD

**Issue by timplication** [oSoc19/opt-horison-hackathon#1]
We have to discuss the following:

- [x] Do we agree upon the deliverables?
- [x] Are the deliverables properly sized? (Not too much work for two days, etc...)
- [x] Who will take ownership of what deliverable? (What would you like to do?)
- [x] Do you have any extra ideas?

**Comment by HunteRoi** [comment]
A kind of summarize would be great for transparency. So here it is!

We have highlighted three deliverables :
1) a dataset from a single starting point based on walking mode - managed by @BertSchoovaerts 
2) an UI visualizer - managed by @HunteRoi (me)
3) the presentation - managed by @timutable 

I guess you (@timutable) are going to help @BertSchoovaerts with building the dataset generator.
